name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions:
  contents: write
  statuses: write

jobs:
  ci_cd:
    runs-on: ubuntu-latest
    steps:
      - name: Set Environment Variable
        env: 
          MY_ENVIRONMENT: "ci-cd-env"
        run:
          echo "Displaying In Terminal MY_ENVIRONMENT=$MY_ENVIRONMENT"
      - name: Call Another Workflow With Secrets
        uses: INF800/test-repo-github-action-workflows/.github/workflows/display.yml@main
        secrets: inherit
        
